"""Step 1 - the test-split firewall.

The problem this solves
-----------------------
KuaiRand-Pure ships the test-window labels in the public download, and the
organizer's `baseline.py:run_fm` reads and prints the test score. The "hidden"
test set is therefore hidden by convention only. An autonomous agent that can
read those labels - deliberately or by accident - invalidates the whole result.

The fix is structural rather than procedural. This module materialises
`work/data_visible/`, a data directory that

  * uses the organizer's exact filenames and column layout, so the untouched
    starter kit (`data.py`, `encode`, ...) works against it verbatim, and
  * physically contains no row dated after the end of the validation window.

Against that directory `data.load()` returns train and valid as normal and an
empty list for test. The agent cannot exfiltrate test labels because they are
not on disk anywhere it can reach.

The randomised-exposure log is a special case. It spans 20220422-20220508,
which straddles both the validation and test windows, and it carries
`long_view` labels. It is truncated to the validation window so that the
unbiased-validation direction stays open without leaking any test-window label.

Run:  python3 -m agent.firewall [--force]
"""
import argparse
import csv
import hashlib
import json
import shutil
import sys
import time
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from agent.paths import (REAL_DATA, VISIBLE_DATA, VISIBLE_MAX_DATE,
                         VISIBLE_MIN_DATE, SPLIT_RANGES)

# Impression logs: filtered by date. Order within each file is preserved,
# which is what keeps submission row_id alignment valid.
LOGS = {
    "log_standard_4_08_to_4_21_pure.csv": (VISIBLE_MIN_DATE, VISIBLE_MAX_DATE),
    "log_standard_4_22_to_5_08_pure.csv": (VISIBLE_MIN_DATE, VISIBLE_MAX_DATE),
    # randomised traffic: validation window only, never the test window
    "log_random_4_22_to_5_08_pure.csv":   SPLIT_RANGES["valid"],
}

# Side tables: no per-impression labels, copied verbatim.
SIDE_TABLES = (
    "user_features_pure.csv",
    "video_features_basic_pure.csv",
    "video_features_statistic_pure.csv",
)

README = """\
# work/data_visible - the agent's view of KuaiRand-Pure

Generated by `agent/firewall.py`. Do not edit by hand; re-run the module.

This directory mirrors the layout of the official `KuaiRand-Pure/data` so the
organizer's `data.py` works against it unmodified. It differs in one respect:

    every impression dated after {maxdate} has been removed.

That is the end of the validation window. The test window (20220429-20220508)
is therefore absent - not masked, not ignored, absent. `data.load()` against
this directory returns an empty list for the 'test' split.

`log_random_4_22_to_5_08_pure.csv` keeps its original name but has been
truncated to the validation window for the same reason.

Row order inside each file is unchanged, so submission `row_id` alignment
against `data.load()[split]` still holds.

See `manifest.json` for row counts and checksums, and
`docs/firewall.md` for the rationale.
""".format(maxdate=VISIBLE_MAX_DATE)


def _sha256(path, chunk=1 << 20):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for blk in iter(lambda: fh.read(chunk), b""):
            h.update(blk)
    return h.hexdigest()


def _filter_log(src, dst, lo, hi):
    """Stream `src` -> `dst` keeping only rows with lo <= date <= hi."""
    kept = dropped = 0
    max_kept = None
    with open(src, newline="") as fin, open(dst, "w", newline="") as fout:
        reader = csv.reader(fin)
        writer = csv.writer(fout)
        header = next(reader)
        writer.writerow(header)
        date_col = header.index("date")
        for rec in reader:
            d = int(rec[date_col])
            if lo <= d <= hi:
                writer.writerow(rec)
                kept += 1
                max_kept = d if max_kept is None else max(max_kept, d)
            else:
                dropped += 1
    return kept, dropped, max_kept


def build(force=False, verbose=True):
    if not REAL_DATA.is_dir():
        raise SystemExit(f"source data not found: {REAL_DATA}")
    if VISIBLE_DATA.exists():
        if not force:
            raise SystemExit(
                f"{VISIBLE_DATA} already exists; pass --force to rebuild")
        shutil.rmtree(VISIBLE_DATA)
    VISIBLE_DATA.mkdir(parents=True)

    manifest = {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "source": str(REAL_DATA),
        "visible_date_range": [VISIBLE_MIN_DATE, VISIBLE_MAX_DATE],
        "excluded_window": list(SPLIT_RANGES["test"]),
        "logs": {},
        "side_tables": {},
    }

    for name, (lo, hi) in LOGS.items():
        src, dst = REAL_DATA / name, VISIBLE_DATA / name
        t0 = time.time()
        kept, dropped, max_kept = _filter_log(src, dst, lo, hi)
        manifest["logs"][name] = {
            "date_filter": [lo, hi],
            "rows_kept": kept,
            "rows_dropped": dropped,
            "max_date_kept": max_kept,
            "sha256": _sha256(dst),
        }
        if verbose:
            print(f"  {name:44s} kept {kept:>9,d}  dropped {dropped:>9,d}"
                  f"  max_date {max_kept}  ({time.time()-t0:.1f}s)")

    for name in SIDE_TABLES:
        src, dst = REAL_DATA / name, VISIBLE_DATA / name
        shutil.copy2(src, dst)
        manifest["side_tables"][name] = {"sha256": _sha256(dst),
                                         "copied_verbatim": True}
        if verbose:
            print(f"  {name:44s} copied verbatim")

    (VISIBLE_DATA / "README.md").write_text(README)
    (VISIBLE_DATA / "manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n")
    return manifest


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--force", action="store_true",
                    help="rebuild even if work/data_visible already exists")
    a = ap.parse_args()
    print(f"building {VISIBLE_DATA} from {REAL_DATA} ...")
    m = build(force=a.force)
    print(f"\ndone. visible window {m['visible_date_range'][0]}"
          f"-{m['visible_date_range'][1]}, "
          f"test window {m['excluded_window'][0]}-{m['excluded_window'][1]} excluded.")
